edition = "2021"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 120
newline_style = "Unix"
overflow_delimited_expr = true
spaces_around_ranges = true
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
style_edition = "2024"
wrap_comments = true
